repos:
  - repo: https://github.com/ambv/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
          - 'PyJWT'
        exclude: (tests/|alembic/)
        language_version: "3.11"
