"""Locust load tests for the notify-server API.

Simulates three types of users:
  - NotificationReader  (weight 6): browses services and notifications
  - SubscriptionManager (weight 1): toggles service subscriptions
  - NotificationPublisher (fixed_count 1): creates notifications (no auth needed)

Run via Docker only:
    docker compose -f docker-compose.yml -f docker-compose.test.yml up locust

Set TOKEN_FILE env var to point to the JSON file generated by scripts/seed_db.py.
"""

import itertools
import json
import os
import random
import sys
from urllib.parse import urlparse

from locust import HttpUser, between, events, task

ALLOWED_HOSTS = {"localhost", "127.0.0.1", "web"}


@events.test_start.add_listener
def on_test_start(environment, **kwargs):
    host = urlparse(environment.host).hostname
    if host not in ALLOWED_HOSTS:
        print(
            f"ABORT: host '{host}' is not allowed. "
            f"Performance tests can only run against: {', '.join(sorted(ALLOWED_HOSTS))}",
            file=sys.stderr,
        )
        environment.runner.quit()


TOKEN_FILE = os.environ.get("TOKEN_FILE", "scripts/test_tokens.json")
API = "/api/v1"

_data = None
_token_cycle = None


def load_test_data():
    global _data, _token_cycle
    if _data is None:
        with open(TOKEN_FILE) as f:
            _data = json.load(f)
        _token_cycle = itertools.cycle(_data["user_tokens"])
    return _data


def next_token():
    """Return tokens round-robin so each Locust user gets a unique one."""
    return next(_token_cycle)


class NotificationReader(HttpUser):
    """Simulates users browsing services and reading notifications."""

    weight = 6
    wait_time = between(1, 3)

    def on_start(self):
        load_test_data()
        token = next_token()
        self.headers = {"Authorization": f"Bearer {token}"}

    @task(3)
    def list_services(self):
        self.client.get(f"{API}/services/", headers=self.headers)

    @task(5)
    def get_user_services(self):
        self.client.get(f"{API}/users/user/services", headers=self.headers)

    @task(10)
    def get_notifications(self):
        limit = random.choice([10, 25, 50, 100])
        self.client.get(
            f"{API}/users/user/notifications",
            params={"limit": limit, "sort": "desc"},
            headers=self.headers,
        )

    @task(2)
    def get_notifications_filtered(self):
        data = load_test_data()
        service_ids = random.sample(
            data["service_ids"], min(3, len(data["service_ids"]))
        )
        self.client.get(
            f"{API}/users/user/notifications",
            params={"limit": 25, "services_id": service_ids},
            headers=self.headers,
            name="GET /users/user/notifications?filtered",
        )


class SubscriptionManager(HttpUser):
    """Simulates users toggling service subscriptions."""

    weight = 1
    wait_time = between(2, 5)

    def on_start(self):
        load_test_data()
        token = next_token()
        self.headers = {"Authorization": f"Bearer {token}"}

    @task
    def toggle_subscriptions(self):
        resp = self.client.get(
            f"{API}/users/user/services",
            headers=self.headers,
            name="[sub] GET services",
        )
        if resp.status_code != 200:
            return
        services = resp.json()
        if not services:
            return
        updates = [
            {"id": s["id"], "is_subscribed": not s["is_subscribed"]}
            for s in random.sample(services, min(3, len(services)))
        ]
        self.client.patch(
            f"{API}/users/user/services",
            headers=self.headers,
            json=updates,
            name="[sub] PATCH services",
        )


class NotificationPublisher(HttpUser):
    """Simulates automated systems creating notifications.

    No auth needed — the endpoint is IP-restricted, and ALLOWED_NETWORKS
    is empty in the test config (all IPs allowed).

    Set fixed_count to 0 to disable during read-only load tests.
    """

    fixed_count = 1
    wait_time = between(1, 2)

    @task
    def create_notification(self):
        data = load_test_data()
        service_id = random.choice(data["service_ids"])
        self.client.post(
            f"{API}/services/{service_id}/notifications",
            json={
                "title": f"Load test alert #{random.randint(1, 100000)}",
                "subtitle": "Automated load test notification",
                "url": "https://notify.example.com/load-test",
            },
            name="POST /services/[id]/notifications",
        )
